[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = ['hardhat/=node_modules/hardhat/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config